In [1]:
import numpy as np 
import pandas as pd

In [3]:
apple = pd.read_csv("myenv/data/APPLE.csv")

apple.rename(columns={'Price':'Date'}, inplace=True)
apple.drop_duplicates()
# apple['Date'].dropna(subset = ['Date'], inplace=True)
# apple['Date'] = pd.to_datetime(apple['Date'])

apple['Close'] = pd.to_numeric(apple['Close'], errors='coerce').round(2)
apple['Open'] = pd.to_numeric(apple['Open'], errors='coerce').round(2)
apple['High'] = pd.to_numeric(apple['High'], errors='coerce').round(2)
apple['Low'] = pd.to_numeric(apple['Low'], errors='coerce').round(2)
apple['Volume'] = pd.to_numeric(apple['Volume'], errors='coerce').round(2)


apple.reset_index(inplace=True, drop=True)

apple['Return'] = apple['Close'].pct_change(fill_method=None).round(3) #Actual Market Movement
apple["Log_returns"] = np.log(apple["Close"] / apple["Close"].shift(1)).round(3) #Accuracy
apple["Volatility"] = apple["Return"].rolling(30).std().round(3) #Risk Measure

apple['Volume_change'] = apple["Volume"].pct_change().round(3)
apple['Volume_group'] = pd.qcut(apple["Volume"], q=3, labels = ["Low", "Medium","High"])
apple['Volume_moving_average'] = apple["Volume"].rolling(20).mean().round(2)

delta = apple["Close"].diff()
gain = (delta.where(delta > 0,0)).rolling(14).mean()
loss = (-delta.where(delta < 0,0)).rolling(14).mean()

rs = gain/loss
apple["RSI"] = 100 - (100 / (1+rs))
apple["RSI"] = apple['RSI'].round(3)
apple["RSI_group"] = pd.qcut(apple["RSI"], q=3 ,labels = ["Low","Medium","High"])



apple.dropna(inplace=True) 
apple

,Date,Close,High,Low,Open,Volume,Return,Log_returns,Volatility,Volume_change,Volume_group,Volume_moving_average,RSI,RSI_group
32,2010-02-17,6.07,6.12,6.02,6.12,436396800.0,-0.003,-0.003,0.021,-0.197,High,825794060.0,44.366,Low
33,2010-02-18,6.08,6.11,6.02,6.04,422825200.0,0.002,0.002,0.021,-0.031,High,816327680.0,54.701,Medium
34,2010-02-19,6.04,6.09,6.03,6.05,415469600.0,-0.007,-0.007,0.021,-0.017,High,806693440.0,64.646,Medium
35,2010-02-22,6.01,6.07,5.97,6.06,390563600.0,-0.005,-0.005,0.021,-0.060,High,782133240.0,59.574,Medium
36,2010-02-23,5.90,6.03,5.86,5.99,575094800.0,-0.018,-0.018,0.021,0.472,High,757603000.0,51.485,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3771,2024-12-24,256.80,256.81,253.90,254.10,23234700.0,0.012,0.011,0.009,-0.431,Low,47062575.0,76.187,High
3772,2024-12-26,257.61,258.69,256.23,256.79,27237100.0,0.003,0.003,0.009,0.172,Low,46125120.0,76.814,High
3773,2024-12-27,254.20,257.29,251.69,256.43,42355300.0,-0.013,-0.013,0.009,0.555,Low,46567965.0,69.306,High
3774,2024-12-30,250.83,252.12,249.39,250.86,35557500.0,-0.013,-0.013,0.010,-0.160,Low,46921770.0,58.385,Medium
3775,2024-12-31,249.06,251.90,248.07,251.07,39480700.0,-0.007,-0.007,0.009,0.110,Low,46488950.0,53.990,Medium

In [4]:
tesla = pd.read_csv("myenv/data/TESLA.csv")
tesla.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [48]:
tesla.rename(columns={'Price':'Date'}, errors= 'coerce', inplace=True)


tesla['Close'] = tesla['Close'].dropna()
tesla['High'] = tesla['High'].dropna()
tesla['Low'] = tesla['Low'].dropna()
tesla['Open'] = tesla['Open'].dropna()
tesla['Volume'] = tesla['Volume'].dropna()


tesla['Close'] = pd.to_numeric(tesla['Close'], errors='coerce').round(2)
tesla['Open'] = pd.to_numeric(tesla['Open'], errors='coerce').round(2)
tesla['High'] = pd.to_numeric(tesla['High'], errors='coerce').round(2)
tesla['Low'] = pd.to_numeric(tesla['Low'], errors='coerce').round(2)
tesla['Volume'] = pd.to_numeric(tesla['Volume'], errors='coerce')

tesla = tesla.drop_duplicates()
tesla = tesla.dropna(subset = ['Date'])
tesla = tesla[tesla['Date'] != 'Ticker']
tesla = tesla[tesla['Date'] != 'Date']

tesla['Date'] = pd.to_datetime(tesla['Date'])

tesla.reset_index(inplace=True, drop = True)



tesla

           Date   Close    High     Low    Open       Volume
0    2010-06-29    1.59    1.67    1.17    1.27  281494500.0
1    2010-06-30    1.59    2.03    1.55    1.72  257806500.0
2    2010-07-01    1.46    1.73    1.35    1.67  123282000.0
3    2010-07-02    1.28    1.54    1.25    1.53   77097000.0
4    2010-07-06    1.07    1.33    1.06    1.33  103003500.0
...         ...     ...     ...     ...     ...          ...
3647 2024-12-24  462.28  462.78  435.14  435.90   59551800.0
3648 2024-12-26  454.13  465.33  451.02  465.16   76366400.0
3649 2024-12-27  431.66  450.00  426.50  449.52   82666800.0
3650 2024-12-30  417.41  427.00  415.75  419.40   64941000.0
3651 2024-12-31  403.84  427.93  402.54  423.79   76825100.0

[3652 rows x 6 columns]